### PR TITLE
Added bokeh browser example

### PR DESCRIPTION
**Pull request by nicain**
Added back in the bokeh browser example.

### CODE REVIEW

**Comment by nicain** [comment]
@dyf Should I merge my own PR?

**Comment by neuromusic** [comment]
iirc the goal this week is to have only the bare necessary infrastructure so participants can build out the repo. next week, we can start pulling in contributions like this.

**Comment by mabuice** [comment]
@nicain Do *not* merge that PR right now

**Comment by nicain** [comment]
Okay. I added @mabuice as a reviewer, when you and @dyf sign off feel free to merge.

**Comment by dyf** [comment]
we've got a lot of activity in the repo now.  merging this.

**Pull request merged**
