### PR TITLE
py3-style explicit import

### PR DESCRIPTION
**Pull request by neuromusic**
untested, but I think this will be more robust

see https://stackoverflow.com/questions/10501473/python-modules-with-identical-names-i-e-reusing-standard-module-names-in-pack

### CODE REVIEW

**Comment by neuromusic** [comment]
cc @dyf

**Comment by fcollman** [comment]
@neuromusic sorry the other PR invalidated this, can you resolve the conflict?

**Comment by neuromusic** [comment]
no worries. I'll resolve it later this afternoon.

**Comment by neuromusic** [comment]
despite looking a bit more complicated, my understanding of the current __init__.py solution is that it will not work properly if e.g. a user has a package installed called "modeling" ... the current __init__.py will import that package instead of the subpackage.

this PR fixes that by explicitly importing the subpackages as intended.

**Pull request merged**
