### PR TITLE
added print_lmao function. Very useful if you are laughing.

### PR DESCRIPTION
**Pull request by fbolanos**
Hi there, here's my pull request. Please use this function wisely.

### CODE REVIEW

**Comment by neuromusic** [comment]
this will throw an error on python 2 without `from __future__ import print_function`

**Comment by fbolanos** [comment]
Tested the function on:

> Linux CorticalPad 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

With conda -V
> conda 4.3.21

And on a python shell running:
> Python 2.7.13 

The output was lmao as expected :smile: 

image

**Comment by mabuice** [comment]
>>> ("lmao") is "lmao"
True

Justin, I need a "tsk" emoji.  :)

**Comment by neuromusic** [comment]
gah! shame on me!!!

**Comment by neuromusic** [comment]
seems like we need to get a test suite set up.... @fcollman?

**Pull request closed without merging**
